export const recruiterOnboardFromControls = [
  {
    label: "Name",
    name: "name",
    placeholder: "Enter your name",
    componentType: "input",
    type: "",
  },
  {
    label: "Company Name",
    name: "companyName",
    placeholder: "Enter your company name",
    componentType: "input",
    type: "",
  },
  {
    label: "Company Role",
    name: "companyRole",
    placeholder: "Enter your company role",
    componentType: "input",
    type: "",
  },
];
export const initialRecruiterFromData = {
  name: "",
  companyName: "",
  companyRole: "",
};
export const candidateOnboardFormControls = [
  {
    label: "Resume",
    name: "resume",
    componentType: "file",
    type: "file",
  },
  {
    label: "Name",
    name: "name",
    placeholder: "Enter your name",
    componentType: "input",
    type: "",
  },
  {
    label: "Current Company/College",
    name: "currentCompany",
    placeholder: "Enter your current company",
    componentType: "input",
    type: "",
  },
  {
    label: "Current Job Location",
    name: "currentJobLocation",
    placeholder: "Enter your current job location",
    componentType: "input",
    type: "",
  },
  {
    label: "Preffered Job Location",
    name: "prefferedJobLocation",
    placeholder: "Enter your preffered job location",
    componentType: "input",
    type: "",
  },
  {
    label: "Current Salaray",
    name: "currentSalary",
    placeholder: "Enter your current salary",
    componentType: "input",
    type: "number",
  },
  {
    label: "Notice Period",
    name: "noticePeriod",
    placeholder: "Enter your notice period",
    componentType: "input",
    type: "number",
  },
  {
    label: "Skills",
    name: "skills",
    placeholder: "Enter your skills",
    componentType: "input",
    type: "",
  },
  {
    lael: "Previous Companies",
    name: "previousComapanies",
    placeholder: "Enter your previous companies",
    componentType: "input",
    type: "",
  },
  {
    label: "Total Experience",
    name: "totalExperience",
    placeholder: "Enter your total experience",
    componentType: "input",
    type: "number",
  },
  {
    label: "College",
    name: "college",
    placeholder: "Enter your college",
    componentType: "input",
    type: "",
  },
  {
    label: "College Location",
    name: "collegeLocation",
    placeholder: "Enter your college location",
    componentType: "input",
    type: "",
  },
  {
    label: "Graduated Year",
    name: "graduatedYear",
    placeholder: "Enter your graduated year",
    componentType: "input",
    type: "number",
  },
  {
    label: "Linkedin Profile",
    name: "linkedinProfile",
    placeholder: "Enter your linkedin profile URL",
    componentType: "input",
    type: "",
  },
  {
    label: "Github Profile",
    name: "githubProfile",
    placeholder: "Enter your github profile url",
    componentType: "input",
    type: "",
  },
];

export const initialCandidateFromData = {
  resume: "",
  name: "",
  currentCompany: "",
  currentJobLocation: "",
  prefferedJobLocation: "",
  currentSalary: "",
  noticePeriod: "",
  skills: "",
  previousComapanies: "",
  totalExperience: "",
  college: "",
  collegeLocation: "",
  graduatedYear: "",
  linkedinProfile: "",
  githubProfile: "",
};
export const postNewJobFormControls = [
  {
    label: "Company Name",
    name: "companyName",
    placeholder: "Company Name",
    componentType: "input",
    type: "",
    disabled: true,
  },
  {
    label: "Title",
    name: "title",
    placeholder: "Job Title",
    componentType: "input",
    type: "",
  },
  {
    label: "Type",
    name: "type",
    placeholder: "Job Type (Full-time/Part-time/Contract)",
    componentType: "input",
    type: "",
  },
  {
    label: "Location",
    name: "location",
    placeholder: "Job Location",
    componentType: "input",
    type: "",
  },
  {
    label: "Experience",
    name: "experience",
    placeholder: "Minimum Experience (Years)",
    componentType: "input",
    type: "number",
  },
  {
    label: "Skills",
    name: "skills",
    placeholder: "Skills Required",
    componentType: "input",
    type: "",
  },
];
export const initialPostNewJobFormData = {
  companyName: "",
  title: "",
  type: "",
  location: "",
  experience: "",
  description: "",
  skills: "",
};
